../Modules/000-common.core/000-Constants.vhd 
../Modules/000-common.core/003-INSTR_CODES.vhd 
../Modules/000-common.core/004-ALU_TYPE.vhd
../Modules/a.b-Datapath.core/ALUComponents/a.b.b.e.a-Comparator.vhd 
../Modules/a.b-Datapath.core/ALUComponents/a.b.b.b-Logic.vhd 
../Modules/a.b-Datapath.core/ALUComponents/a.b.b.c-mux41_Generic.vhd 
../Modules/a.b-Datapath.core/ALUComponents/a.b.b.d-Shifter.vhd 
../Modules/a.b-Datapath.core/ALUComponents/a.b.b.e-Toplevelcomparator.vhd 
../Modules/a.b-Datapath.core/ALUComponents/a.b.b.a-P4_Adder/fa.vhd 
../Modules/a.b-Datapath.core/ALUComponents/a.b.b.a-P4_Adder/G.vhd 
../Modules/a.b-Datapath.core/ALUComponents/a.b.b.a-P4_Adder/iv.vhd 
../Modules/a.b-Datapath.core/ALUComponents/a.b.b.a-P4_Adder/nd2.vhd 
../Modules/a.b-Datapath.core/ALUComponents/a.b.b.a-P4_Adder/mux21_generic.vhd 
../Modules/a.b-Datapath.core/ALUComponents/a.b.b.a-P4_Adder/Pg.vhd 
../Modules/a.b-Datapath.core/ALUComponents/a.b.b.a-P4_Adder/PgNetwork.vhd 
../Modules/a.b-Datapath.core/ALUComponents/a.b.b.a-P4_Adder/sparsetree.vhd 
../Modules/a.b-Datapath.core/ALUComponents/a.b.b.a-P4_Adder/carryselect.vhd 
../Modules/a.b-Datapath.core/ALUComponents/a.b.b.a-P4_Adder/sum_generator.vhdl 
../Modules/a.b-Datapath.core/ALUComponents/a.b.b.a-P4_Adder.vhd 
../Modules/a.b-Datapath.core/a.b.a-RF.vhd 
../Modules/a.b-Datapath.core/a.b.b-ProALU.vhd 
../Modules/a.b-Datapath.core/A_register.vhd 
../Modules/a.b-Datapath.core/B_register.vhd
../Modules/a.b-Datapath.core/comp4Branch.vhd 
../Modules/a.b-Datapath.core/FA.vhd 
../Modules/a.b-Datapath.core/FF.vhd 
../Modules/a.b-Datapath.core/IR0_Register.vhd 
../Modules/a.b-Datapath.core/mux2x1.vhd 
../Modules/a.b-Datapath.core/mux4x1.vhd 
../Modules/a.b-Datapath.core/oneBitMux2x1.vhd 
../Modules/a.b-Datapath.core/RCA.vhd 
../Modules/a.b-Datapath.core/register.vhd 
../Modules/a.b-Datapath.core/sgn_extender.vhd 
../Modules/a.a-CU.vhd 
../Modules/a.b-Datapath.vhd 
../Modules/a.c-HU.vhd 
../Modules/a-CPU.vhd
